on:
  workflow_dispatch:
  push:
    branches:
      - 'main'

jobs:
  compute-suffix:
    runs-on: ubuntu-latest
    if: github.repository == 'SouthFox-D/mastodon'
    steps:
      - id: version_vars
        env:
          TZ: Etc/UTC
        run: |
          echo mastodon_version_metadata=+$(date +'%Y-%m-%d')>> $GITHUB_OUTPUT
    outputs:
      metadata: ${{ steps.version_vars.outputs.mastodon_version_metadata }}

  build-image:
    needs: compute-suffix
    uses: ./.github/workflows/build-container-image.yml
    with:
      file_to_build: Dockerfile
      platforms: linux/amd64
      push_to_images: |
        southfox09/mastodon
      version_metadata: ${{ needs.compute-suffix.outputs.metadata }}
      labels: |
        org.opencontainers.image.description=Nightly build image used for testing purposes
      flavor: |
        latest=auto
      tags: |
        type=raw,value=latest
        type=schedule,pattern=${{ needs.compute-suffix.outputs.metadata }}
    secrets: inherit

  build-image-streaming:
    needs: build-image
    uses: ./.github/workflows/build-container-image.yml
    with:
      file_to_build: streaming/Dockerfile
      platforms: linux/amd64
      push_to_images: |
        southfox09/mastodon-streaming
      version_metadata: ${{ needs.compute-suffix.outputs.metadata }}
      labels: |
        org.opencontainers.image.description=Nightly build image used for testing purposes
      flavor: |
        latest=auto
      tags: |
        type=raw,value=latest
        type=schedule,pattern=${{ needs.compute-suffix.outputs.metadata }}
    secrets: inherit
